[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyLOCO"
version = "0.4.0"
dependencies = [
  "accelerator-toolbox",
  "h5py",
  "matplotlib",
  "numpy",
  "PyYAML",
  "tomli; python_version < '3.11'",
]

[project.optional-dependencies]
gui = ["PySide6", "matplotlib"]
pysc-demo = ["accelerator-commissioning==1.5.2"]

[project.scripts]
pyloco-gui = "pyLOCO.gui.app:main"
pyloco-measure = "pyLOCO.measure.app:main"
pyloco-correct = "pyLOCO.correct.app:main"

[tool.hatch.build]
artifacts = ["pyLOCO/gui/assets/*.png"]
